feat: next auth 프로젝트 연동
Kernel360/FE1_E2E_sumtime pull request #49
Opened 2024-08-02 07:03 UTC by Yejin0O0

- Close #37 

## What is this PR? 🔍

- 기능 : next auth를 프로젝트에 연동하였습니다. 
- issue : #37 

## Changes 📝
google OAuth 적용하여 next auth를 프로젝트에 연동하였습니다. 

## ScreenShot 📷

## Precaution

2024-08-02 07:28 UTC, dmdgpdi approved these changes
확인했습니다. 고생하셨습니다!

2024-08-02 12:31 UTC, haejinyun requested changes
수고하셨습니다!!

소셜 로그인 연동이 문서도 많이 보시고 고생하셨을 것 같아요..
제 생각이나 이렇게 바꿔보면 어떄요~~ 하는 부분을 적어보았어요!

현재는 로그인을 성공해도 리다이텍트가 안되고 있는데, 구글 OAuth에서 로그인 성공 후 리다이렉을 하려면 구글 OAuth 클라이언트 관리 페이지에서 사용할 설정할 수 있는 것으로 문서를 많이 보았는데 해당 부분도 확인 부탁드립니다!

그리고 로그아웃을 하고 다시 로그인을 하면 이전의 캐시가 남아있어서 그런지 해당 계정으로 바로 로그인이 되더라구요. 만약 다른 goggle계정으로 로그인하고 싶을 경우가 있을 것 같아 해당 부분도 캐시를 날리든, 해결 방법이 필요할 것이라는 생각이드네요!

또 하나의 생각은 로그인을 하고 받는 유저 정보와 같은 부분을 전역상태로 관리하는 것은 어떨까요?

다시 한 번 너무 수고하셨습니다!!😸

2024-08-02 12:31 UTC, haejinyun commented on .gitignore
> +.env
추가 되었군요..!!!

2024-08-02 12:31 UTC, haejinyun commented on src/app/layout.tsx
>  }
해당 부분에  대한 전체적인 궁금증입니다!
`const session = await getServerSession(authOptions);`
session을 불러와서 `SessionProviderWrapper`에 내려주는 이유가 궁금합니다
`getServerSession`해당 함수의 경우 현재 auth 정보를 가져오는 함수라고 알고있습니다.

그러나 지금 코드를 살펴 보았을 때 todo 페이지에서 또한 위 함수를 사용하여 auth정보를 확인하고 없다면 메인 페이지로 리다이렉트 시키는 코드를 보았는데 여기서 auth 정보를 가져와 provider로 내려주는 이유가 궁금합니다.

해당 부분으로 인하여 `RootLayout`가 async 함수가 되는것도 조금은 찜찜하기도 합니다..(완전 개인적인 의견)


```tsx
import type { Metadata } from 'next';
import './globals.css';
import SessionProviderWrapper from '@/components/common/SessionProviderWrapper';

export const metadata: Metadata = {
  title: 'SumTime',
  description: 'kernel FE E2E project',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="kr">
      <body>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
```
위 get함수가 빠진다면 아래와 같아질 것입니다.

```tsx
'use client';

import { SessionProvider } from 'next-auth/react';
import { ReactNode } from 'react';

interface Props {
  children: ReactNode;
}

function SessionProviderWrapper({ children }: Props) {
  return <SessionProvider>{children}</SessionProvider>;
}

export default SessionProviderWrapper;

```
또한 SessionProviderWrapper도 이렇게 바뀔 것입니다.

2024-08-02 12:31 UTC, haejinyun commented on src/app/layout.tsx
> +        <SessionProviderWrapper session={session}>{children}</SessionProviderWrapper>
context와 관련된 것은 따로 context 폴더를 만드는 것은 어떤가요?
종종 그렇게 관리하는 곳도 보았던 것 같아요~
또한, wrapper라는 네이밍도 좋지만, Auth관련 provider니까 AuthProvider이런 네이밍도 나쁘지 않아보입니다~~

2024-08-02 12:31 UTC, haejinyun commented on src/app/todo/page.tsx
> +      {session?.user?.image && <img src={session?.user?.image} alt="프로필" />}
image를 렌더링 하는 부분에서는 조건부로 유효성을 확인하고 렌더링 해주셨는데
name부분에서는 그러지 않은 이유가 있으실까요?

사실 저는 옵셔널 체이닝을 사용하기보다는 앞에서 값에 대한 유효성을 검증한뒤 &&로 하는 것이 조금 더 명시적이지 않나라는 생각이 들기도 합니다. 혹은 삼항 연산을 써서 값이 없을 경우, 대체 이미지를 보여줄 수도 있다고 생각합니다.
해당 부분에 대해서는 어떻게 생각하시나요?

2024-08-02 12:31 UTC, haejinyun commented on src/app/todo/page.tsx
> +      {session?.user?.image && <img src={session?.user?.image} alt="프로필" />}
```suggestion
      {session.user?.image && <img src={session.user.image} alt="프로필" />}
```
앞쪽에서 유효성 검사를 해주었다면 뒷 부분에서는 체이닝을 걸어줄 필요가 없습니다!
확인해보니 session.user에는 체이닝을 걸지 않아도 괜찮더라구요~

2024-08-02 12:31 UTC, haejinyun commented on src/app/todo/page.tsx
> +    </>
```suggestion
    <>
      {session?.user && (
        <>
          <p>Welcome to the App, {session.user.name}!</p>
          {session.user.image ? (
            <img src={session.user.image} alt="프로필" />
          ) : (
            <img src="~~" alt="프로필" />
          )}
        </>
      )}
      <SignOutButton />
    </>
```
아니면 유효성을 컴포넌트 최상단에 걸어주는 것도 좋을 것 같아요~

2024-08-05 01:34 UTC, Yejin0O0 commented on src/app/todo/page.tsx
> +      {session?.user?.image && <img src={session?.user?.image} alt="프로필" />}
lint 오류 때문에 image 렌더링 부분에만 유효성을 확인하였습니다!
해진님 말대로, 로그인된 유저의 정보와 관련된 부분이라면 일관성 있게 전부 유효성 검사를 하는 것이 필요해 보이네요!!
다만, 해당 코드는 google OAuth가 제대로 이루어졌는지 확인하는 코드로, 삭제될 코드입니다!

다음에 로그인 된 유저의 정보를 확인하는 기능에서 해진님의 의견을 반영하여  컴포넌트 최상단에 유효성 검사를 하겠습니다~!! 
이미지의 경우 대체 이미지를 렌더링 하는 방향으로 진행해보도록 하겠습니다!!

좋은 의견 감사합니다!!

2024-08-05 01:41 UTC, Yejin0O0 commented on src/app/layout.tsx
>  }
Layout.tsx는 메인페이지와 todo 페이지 상위에 있는 레이아웃입니다. 즉, Layout.tsx는 최상위 컴포넌트라고 할 수 있습니다. 

사용자의 권한 정보를 최상단 컴포넌트에서 불러와야 한다고 생각해서, 해당 위치에 auth 정보를 가지고 오는 코드를 작성하였습니다. 

해진님의 말을 듣고 보니, 저도 RootLayout에 aysnc를 쓰는것이 찜찜해지네요,,, 해당 부분 확인 후 다시 commit 해보도록 하겠습니다! 

좋은 의견 감사합니다!

2024-08-05 01:43 UTC, Yejin0O0 commented on src/app/layout.tsx
> +        <SessionProviderWrapper session={session}>{children}</SessionProviderWrapper>
AuthProvider 좋은 이름이네요!! 해당 부분 반영해서 commit 하겠습니다!

context 폴더는 나중에 관련 컴포넌트들이 더 많아졌을 때 생성하는 것도 나쁘지 않다고 생각합니다..!

2024-08-05 05:44 UTC, Yejin0O0 commented on src/app/layout.tsx
>  }
getServerSession은 sever 컴포넌트에서만 사용 가능합니다. SessionProvider는 client 컴포넌트에서만 사용 가능합니다. 

위 두 조건으로 인해 SessionProviderWrapper 컴포넌트는 session이라는 props를 받을 수 밖에 없는 구조입니다..!

aysnc 함수가 RootLayout에 쓰이는게 찜찜하다고 하셔서, 해당 부분을 디렉터님에게 여쭤봤는데, RootLayout에 쓰는 것은 크게 문제 될 것이 없다라고 답변 주셨습니다. 또 많은 provider가 추가될 수 있는데, 해당 부분을 app 컴포넌트를 생성해서 관리할 수도 있다는 것을 언급해주셨습니다. 

app 컴포넌트를 생성하게 된다면 RootLayout에선 async 함수를 쓰지 않아도 되어, 이후 작업에 만일 provider가 더 추가된다면 app 컴포넌트를 생성하여 코드 리팩토링을 진행하도록 하겠습니다! 

다시 한번 좋은 의견 감사합니다!

2024-08-05 07:58 UTC, haejinyun approved these changes
수고하셨습니다!

2024-08-05 09:22 UTC, merged