feat:  Todo CRUD 작업시 화면 갱신되도록 TanstackQuery 적용
Kernel360/FE1_E2E_sumtime pull request #78
Opened 2024-08-07 07:14 UTC by enigsuss

- Close #67

## What is this PR? 🔍

- 기능 : TodoPage에서 현재 구현된 모든 기능에 Tanstack Query 적용
- issue : #67 

## Changes 📝
TanstackQuery를 적용하여 fetching 작업 이후 화면이 즉시 업데이트 되도록 변경하였습니다.

## ScreenShot 📷

## Precaution

2024-08-07 07:43 UTC, godhyzzang commented on src/components/todo/index.tsx
> +  const { mutate: updateTodo } = useUpdateTodo();
method 중 get을 제외하고 put, delete, post에 mutation을 사용하는 방식으로 쓰였군요.
get방식은 Mutation이 아니라 refetch를 사용헀는데 관련해서 어떤 방식으로 동작하는지는 더 공부해봐야겠습니다.!

수고하셨습니다!

2024-08-07 07:45 UTC, godhyzzang commented on src/components/todo/index.tsx
> +  const { value: isModalOpen, setTrue: setIsModalOpenTrue, setFalse: setIsModalOpenFalse } = useBooleanState();
value: isModalOpen만 있었는데 setTrue, setFalse에도 alias달아주셨군요!
덕분에 setTrue, setFalse가 아니라 setIsModalOpenTrue,setIsModalOpenFalse를 사용할 수 있어서 사용하기에 훨씬 편한 것 같습니다~

2024-08-07 07:57 UTC, godhyzzang commented on src/components/todo/index.tsx
> +      setModalTodo(todoData || null);
여기에서 isTodoDataSuccess && todoData 가 있어야 setModalTodo 훅이 실행되는 거라면 
setModalTodo(null)이 실행되는 경우는 없지 않을까요???

setModalTodo(todoData)로 바꾸는 편이 혼동방지 차원에서 좋을 것 같습니다!

2024-08-07 07:58 UTC, godhyzzang commented on src/components/todo/index.tsx
> +      setModalTodo(todoData || null);
여기에서 isTodoDataSuccess && todoData 가 있어야 setModalTodo 훅이 실행되는 거라면 
setModalTodo(null)이 실행되는 경우는 없지 않을까요???

setModalTodo(todoData)로 바꾸는 편이 혼동방지 차원에서 좋을 것 같습니다!

2024-08-07 08:30 UTC, godhyzzang commented on src/app/apiTest/hooks/todoQueries.ts
> +      createTodo(userId.toString(), title, content, startTime, endTime, color),
createTodo에 todoId도 추가되어야 할 것 같습니다!

2024-08-07 08:30 UTC, enigsuss commented on src/components/todo/index.tsx
> +      setModalTodo(todoData || null);
네 수정했습니다:)

2024-08-07 08:35 UTC, haejinyun requested changes
mutate 반영해주셨네요!!
이왕 사용하기로 한 tanstack query의 다양한 속성을 잘 활용해보죠!!

refetch를 사용하기 보다는 mutate가 onSuccess 후의 invalidate를 사용하는 방향이 더 낫다고 생각합니다. 코드 양도 줄어들고, 코드를 작성하다가 깜빡할 일도 적으니까요
다양하게 적어보았는데 리뷰 중 이해가 안되는 것이나 생각하신 것과 다른 것이 있다면 말씀해주세요!

수고 많으셨습니다!!

2024-08-07 08:35 UTC, haejinyun commented on src/app/apiTest/hooks/todoQueries.ts
> +  getOneByTodoId,
어떤 것을 하나 가져오는 것인지도 네이밍에서 들어나면 좋을 것 같습니다!

2024-08-07 08:35 UTC, haejinyun commented on src/app/apiTest/hooks/todoQueries.ts
> +import { useMutation, UseMutationResult, useQuery, UseQueryResult } from '@tanstack/react-query';
하나에 몰아넣기보다는 useQuery를 쓰는 것과 mutate하는 것과 분리를 해도 좋을 것 같아요.

2024-08-07 08:35 UTC, haejinyun commented on src/app/apiTest/hooks/todoQueries.ts
> +export const useUpdateTodoTime = (): UseMutationResult<
```suggestion
  });
  
export const useUpdateTodoTime = (): UseMutationResult<
```
다른 사람이 볼 때, 이것을 읽을 때도 고려해주면 좋을 것 같아요 ~
예시로 함수별로 줄바꿈을 넣는 등이 있을 것 같아요!

2024-08-07 08:35 UTC, haejinyun commented on src/app/apiTest/hooks/todoQueries.ts
> +      createTodo(userId.toString(), title, content, startTime, endTime, color),
`userId.toString()`
해당 부분에 대한 의문이 조금 드네요
db상에서도 보통 userId의 경우는 number 즉 숫자로 타입이 정의되는 경우가 일반적인데 관련 함수나 관리를 따로 string으로 하는 이유가 있을까요?

db상에서 관리가 되는 것이 number 라면 그 타입을 유지시키는 것이 맞다고 느껴집니다.
다른 사람이 이 코드를 보았을 때, 이게 익숙하게 받아들여지지는 않을 것 같습니다..!

2024-08-07 08:35 UTC, haejinyun commented on src/app/apiTest/hooks/todoQueries.ts
> +  });
```suggestion
interface UpdateTodoVariables {
  todoId: string;
  title: string;
  content: string;
  startTime: string;
  endTime: string;
  color: string;
}

export const useUpdateTodo = (): UseMutationResult<SelectTodo, Error, UpdateTodoVariables> => {
  const queryClient = useQueryClient();
  return useMutation<SelectTodo, Error, UpdateTodoVariables>({
    mutationFn: ({ todoId, title, content, startTime, endTime, color }) =>
      updateTodo(todoId, title, content, startTime, endTime, color),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['todos'] });
    },
  });
};
```

`queryClient.invalidateQueries` 를 활용한다면 굳이 refetch를 해주지 않아도 됩니다.
이는 mutate가 성공하였을 경우 `todos`로 시작하는 쿼리키의 캐시를 날려 해당 쿼리 요청을 새롭게 해줍니다.
이렇게 된다면 다른 파일에 달려있는 새로고침목적을 위한 refetch를 지울 수 있다고 생각합니다.

2024-08-07 08:35 UTC, haejinyun commented on src/components/todo/index.tsx
> +  const [todos, setTodos] = useState<SelectTodo[]>([]);
위 코드는 임시인 것인가요?
쿼리를 통해 값을 가져오는데 이를 다시 state에 담아준 이유가 궁금합니다.

2024-08-07 08:35 UTC, haejinyun commented on src/components/todo/index.tsx
> +  }, [todoListData]);
또한 useEffect를 사용한 이유도 궁금합니다!
여기서는 todoListData를 get해온 것을 바로 사용하면 되지 않을까?라는 생각이 드네요
만약 return 하는 곳에서 undefined인 값이 있다며 에러가 난다면 앞에서 `todoListData&&(~~)`이런 식으로 유효성 검사를 해준 뒤에 코드를 진행하는 것이 값에 대한 확실성을 줄 것 같기도 합니다!

2024-08-07 08:35 UTC, haejinyun commented on src/components/todo/index.tsx
> +  const handleSave = async (title: string, content: string, startTime: string, endTime: string, color: string) => {
위 함수는 modal에 값이 있을 경우 없을 경우로 진행하기보다는 각각 함수를 분리하는 것이 명시적이라고 생각이 듭니다!

2024-08-07 08:35 UTC, haejinyun commented on src/components/todo/index.tsx
> +        },
이런 부분은 이제 앞서 말씀드린 내용을 고려해주신다면 여기서 refetch가 일어나기보다는 mutate를 하는 곳에서 onSuccess/ onError를 통해서 관리 할 수 있을 것 같습니다.

2024-08-07 08:35 UTC, enigsuss commented on src/app/apiTest/hooks/todoQueries.ts
> +      createTodo(userId.toString(), title, content, startTime, endTime, color),
db에서 todoid를 PK, autoincrement로 지정했기 때문에 todoId는 내부에서 자동으로 생성됩니다. 그래서 클라이언트 코드에서는 todoId를 추가하지 않아도 됩니다:)

2024-08-07 09:54 UTC, haejinyun approved these changes
빠른 다음 작업을 위해서 approve 하겠습니다.

2024-08-08 08:52 UTC, enigsuss commented on src/app/apiTest/hooks/todoQueries.ts
> +  getOneByTodoId,
넵 수정했습니다:)

2024-08-08 08:52 UTC, enigsuss commented on src/app/apiTest/hooks/todoQueries.ts
> +import { useMutation, UseMutationResult, useQuery, UseQueryResult } from '@tanstack/react-query';
넵 참고할게요!

2024-08-08 08:52 UTC, enigsuss commented on src/app/apiTest/hooks/todoQueries.ts
> +export const useUpdateTodoTime = (): UseMutationResult<
네 적용했습니다:)

2024-08-08 08:53 UTC, enigsuss commented on src/app/apiTest/hooks/todoQueries.ts
> +      createTodo(userId.toString(), title, content, startTime, endTime, color),
리팩터링 과정에서 저도 타입 일치의 필요성을 느꼈습니다. 다음 커밋에 반영하겠습니다:)

2024-08-08 08:54 UTC, enigsuss commented on src/app/apiTest/hooks/todoQueries.ts
> +  });
조언 감사합니다. 적용했습니다 :)

2024-08-08 08:56 UTC, enigsuss commented on src/components/todo/index.tsx
> +  const [todos, setTodos] = useState<SelectTodo[]>([]);
말씀하신 것처럼 쿼리에서 직접 가져오는 것이 좋은 것 같습니다. 적용했습니다 :)

2024-08-08 08:57 UTC, enigsuss commented on src/components/todo/index.tsx
> +  }, [todoListData]);
수정했습니다 :)

2024-08-08 08:57 UTC, enigsuss commented on src/components/todo/index.tsx
> +  const handleSave = async (title: string, content: string, startTime: string, endTime: string, color: string) => {
분리 진행했습니다:)

2024-08-08 08:58 UTC, enigsuss commented on src/components/todo/index.tsx
> +        },
네 반영했습니다 :)

2024-08-08 09:13 UTC, godhyzzang commented
현재는 기능만 동작하는 수준으로 구현된 상태라 코드 가독성 등 리팩토링은 추후에 이루어질 예정입니다..!

2024-08-08 09:14 UTC, godhyzzang approved these changes
제대로 동작합니다~함께 수고 많으셨습니다

2024-08-08 09:15 UTC, haejinyun approved these changes

2024-08-08 09:28 UTC, merged